### ISSUE TITLE
Games with add-ons won't load

### ISSUE THREAD

**Issue by myeuropeanPAL** [wiiu-env/Aroma#10]
When tying to load games with add-ons installed I receive the following error message:
There is an error in he add-on contect data. Go To Data Management in System Seings to delete the add-on content.

Tried with two games so far with Aroma beta-6, the same games with the add-on load fine with Tiramisu.
Both game and add-on is installed on a usb drive, after deleting the add-on the games load fin in Aroma too.

**Comment by Maschell** [comment]
Looks like you have pirated the DLC instead of buying them in the eshop. Buy the DLC and try again
