### ISSUE TITLE
Do you plan to add (or does it have) debug features for homebrew developers ?

### ISSUE THREAD

**Issue by SeleDreams** [wiiu-env/Aroma#21]
Hi, I'm a homebew developer and I was wondering if Aroma would make it more convenient to develop and debug wii u homebrews ? because at the moment the process is pretty inconvenient, it would be way better to be able to directly send the builds to the wii u through wifi/lan and be able to debug with GDB through there as well. would aroma allow it ?

**Comment by Maschell** [comment]
You can already load homebrew via the network with [wiiload](https://github.com/wiiu-env/wiiload_plugin).

A GDB stub is in progress but still has some bugs.

**Comment by SeleDreams** [comment]
> The [gdbstub_plugin](https://github.com/wiiu-env/gdbstub_plugin) has been released :)

that's pretty nice, is there also a way to send the homebrews from the pc to the wii u remotely ? something like the homebrew launcher's netloader on 3ds for instance, it should make it faster to debug
