### ISSUE TITLE
White screen with Wii U sign when launching aroma

### ISSUE THREAD

**Issue by NormanFoxLee** [wiiu-env/Aroma#22]
I used it on a fresh Wii U with 5.5.6 firmware.

1. Have Tiramisu installed and working by using this guide: https://wiiu.hacks.guide/#/tiramisu/sd-preparation
2. Download default Payloads, Base and Plugins from https://aroma.foryour.cafe/ (Aroma Beta-10b)
3. Upload files on SD card
4. In EnvironmentLoader select aroma

Actual Result:
White screen with Wii U sign

Expected Result:
Aroma was booted

In additional I added 01_sigpatches.rpx into aroma files but still the same result.
Aroma Beta-9 works fine. I deleted all 10b files and downloaded Beta-9 release.

**Comment by Maschell** [comment]
Can you try again with latest beta?

**Comment by miguelsanzpardo** [comment]
I am having similar problem using aroma beta 14.
Once I select from the environment Menu "aroma" I get stuck in white screen with wiiu logo.
I dont have any problem when I select Tiramisu from the menu.

**Comment by Mannygamesyeet** [comment]
same

**Comment by NormanFoxLee** [comment]
I transferred my account on new Wii U and repeated the installation process with Beta-16 this time.
Works fine.
