### ISSUE TITLE
Cheat Plugin

### ISSUE THREAD

**Issue by AnalogHero** [wiiu-env/Aroma#23]
Hi Maschell,

do you think its somehow possible to add a cheat plugin in Aroma?
I really appreciate you work.
Thank you for your time on this project.

Regards,
AnalogHero

**Comment by Natedogwoooof** [comment]
pretendo wouldn't be happy tho

**Comment by CommanderGL** [comment]
Can you please close this issue as this is not something in aroma itself it would be a separate unofficial plugin.
