### ISSUE TITLE
Installed homebrew NOT appearing on wii u menu

### ISSUE THREAD

**Issue by Chibi-Usa** [wiiu-env/Aroma#24]
as title states i have the latest version of aroma, but a large portion of my installed homebrew isnt present on the menu

**Comment by Maschell** [comment]
What do you mean by "installed" homebrew? All .rpx and .wuhb files inside `sd:/wiiu/apps` will show up on the wii u menu on Aroma. If you're talking about `.elf` homebrews: they are **NOT** compatible with Aroma an never will be.

**Comment by Chibi-Usa** [comment]
its several .rpx files not appearing

i forget which as i dont usually mess with homebrew unless i want to mess with homebrew

**Comment by Maschell** [comment]
I am sorry, but if you can't even remember which apps where not showing up in the menu, how would I be able to reproduce and fix it?

**Comment by Chibi-Usa** [comment]
I was having issues with aroma and the environment loader so I was unable
to load said homebrew, I will update later with said applications that did
not appear on the aroma environment

**Comment by Chibi-Usa** [comment]
actually found out the issue, for some reason the aroma verisons that i installed via the homebrew app store, didnt actually download, i have manually added the files to my sd card and now it works

human stupidity ftw
