### ISSUE TITLE
Wii U Unable to Transfer Miis to 3DS via Local Network

### ISSUE THREAD

**Issue by TheMCSpacePro** [wiiu-env/Aroma#25]
When attempting to transfer Miis from the Wii U to 3DS through the standard method (connect the systems up via a local network through the Mii Maker itself), the Wii U never pops up in the "Search for Players" option on the 3DS side _**UNLESS**_ Aroma is not active (i.e.: the Wii U was booted **_WITHOUT_** the SD card).

**Comment by Maschell** [comment]
Has been fixed in the latest [AromaBasePlugin nightly](https://github.com/wiiu-env/AromaBasePlugin/releases/tag/AromaBasePlugin-20230222-151948) and will be in the next Aroma Beta

**Comment by TheMCSpacePro** [comment]
Ok, should I go ahead and close this then?

**Comment by Maschell** [comment]
I will close it once its fully released

**Comment by Maschell** [comment]
Fixed in https://github.com/wiiu-env/Aroma/releases/tag/beta-12
