### ISSUE TITLE
Rayman Legends launched from Quick Start menu freezes console

### ISSUE THREAD

**Issue by Andrew1Hawes** [wiiu-env/Aroma#26]
Freezes on the white screen with the Wii U logo in the bottom right corner and the sound loops forever. Game opens, plays, and closes fine when launched normally.

Log attached.
[30.log](https://github.com/wiiu-env/Aroma/files/10932002/30.log)

**Comment by Maschell** [comment]
Fixed with https://github.com/wiiu-env/WUMSLoader/commit/f7f8b007facd2d099aa295a496f6ef63862690bd

Next Aroma beta with this fix will be released soon
