### ISSUE TITLE
I have been getting the error code 150-3030

### ISSUE THREAD

**Issue by Vadenimo2k21** [wiiu-env/Aroma#28]
Alright. My Wii U SD card slot was broken in 2022, and it got fixed, but whenever I try to install Aroma, I have been getting the error code 150-3030, even if my SD Card is not broken at all. I assume that it has something to do with my manually fixed SD slot, since I tried using multiple SD cards at this point. Is there a possibility to fix it, or should I get a new Wii U console?

**Comment by Vadenimo2k21** [comment]
I should also add the fact that this SD card slot works, because I can use Tiramisu and the Environment Loader without any problems. In fact, I have been using Tiramisu for at least a while with no issues, but since it has not a built-in Mocha plugin, I wanted to switch to Aroma. Otherwise, I cannot check whether I am affected to the newest Wii U problem or not.

**Comment by Maschell** [comment]
150-3030 happens when the wii u menu fails to *write* to the SD Card. Can you check if the sd card (adapter?) is write locked?

For testing: Start the console without any sd card, start mii make, insert the sd card and try to export an mii as image to the sd card. Does this work?

[mdinfo](https://github.com/GaryOderNichts/mdinfo) does also work on Tiramisu

**Comment by Vadenimo2k21** [comment]
Okay, I think I found the problem. My SD Card is not locked at all, BUT the console says it was locked.

**Comment by Maschell** [comment]
I just tried it, works for me on latest Tiramisu. Tiramisu and Aroma both ship with exactly the same MochaPayload. Are you sure you're not loading any other mocha version manually?

**Comment by Vadenimo2k21** [comment]
Nope. I am pretty sure. I cannot use mdinfo on Tiramisu, and I did nothing else than starting the console with Autoboot, selecting Mii Maker, launching HBL, and starting mdinfo.

**Comment by Vadenimo2k21** [comment]
Does the program need permission writing on SD cards, or Mocha? If yes, then well. My console is useless for writing on SD cards, since the slot can only read the cards. As earlier told, the SD slot was manually fixed.

**Comment by Maschell** [comment]
Please redownload Tiramisu, maybe something went wrong while overriding the files. Try to rename the existing wiiu directory and create a new one from the tiramisu zip. Writing to the sd card is not needed

**Comment by Vadenimo2k21** [comment]
> Please redownload Tiramisu, maybe something went wrong while overriding the files. Try to rename the existing wiiu directory and create a new one from the tiramisu zip. Writing to the sd card is not needed

Hm, I could try, but I am not concerned, whether it will work. Still thanks for trying to help me. I’ll send you a message later, when I have tried it. If it still does not work, I’ll give up and hope that my Wii U is not affected of the NAND problem that is causing by a specific chip.

**Comment by Vadenimo2k21** [comment]
Thank you! It did indeed somehow work. I hope this will also fix that Aroma problem.
