### ISSUE TITLE
Aroma locks with error "Failed to resolve dependencies

### ISSUE THREAD

**Issue by emmandyar** [wiiu-env/Aroma#29]
So. I had to use the sd card for other things, I backed it up to my pc (linux) and once restored, aroma failed to load. Fine, I just download the new update with the modules and now it boots aroma, but after the screen glitches and shows the wii u logo again, it defaults to a black screen with that message

**Comment by Maschell** [comment]
Did you already update the "payloads"? You need to update both, "payloads" and "base aroma". Either you have a missing, outdated or corrupted file on the sd card.

Can you check if you have an additional files in `sd:/wiiu/environments/aroma/modules`?

**Comment by emmandyar** [comment]
Ahh dammit, forgot to unzip base-aroma. Had the payloads and the modules.

All is good now. Sorry about that
