### ISSUE TITLE
Built in Mocha not Working (5.5.5U)

### ISSUE THREAD

**Issue by Garynosmash2** [wiiu-env/Aroma#3]
It will not open software installed on both usb or nand. It will also not install things using wup installer. Tiramisu's built in mocha still works, just not aroma.

**Comment by Maschell** [comment]
Piracy is not supported in Aroma

**Comment by Garynosmash2** [comment]
What if I want to use homebrew apps that install to the home menu.

**Comment by danylopez123** [comment]
Oh, that explains why Titles installed in the Wii U NAND will throw an error saying the Nintendo ID thing doesn't have this game anymore and Titles installed in USB with DLC added as well will throw the error with the content and also custom Titles like when i got GTA Vice City for the Wii U will throw an error saying to turn off the Wii U.

Do you think that Aroma will support Piracy like Tiramisu someday?

**Comment by TheMasterCoders** [comment]
just install sigpatches.

**Comment by danylopez123** [comment]
> just install sigpatches.

Like downloading it from https://github.com/marco-calautti/SigpatchesModuleWiiU/releases ?
Or just copying the 01_sigpatches.rpx from Tiramisu to Aroma?

**Comment by Maschell** [comment]
Neither Tiramisu nor Aroma support Piracy and will never support any form of piracy
