### ISSUE TITLE
Quick Start Menu (Disc Games, Aroma) doesn't wait for disc to be loaded before booting games.

### ISSUE THREAD

**Issue by Cueropedo** [wiiu-env/Aroma#30]
Hi, the issue is as follows.
When the Wii U stock boot takes place (default booting), quick start menu waits for the game disc to be fully read before attemping to quick boot it.
However, in EnvironmentLoader Coldboot + Autobooting into Aroma (this affects Tiramisu as well, I did test it), this does not happen.
The result is that the Wii U attempts to boot the game without the disc being fully read, which results on a failure and instead boots the Wii U Menu. However, if you wait for the disc to be fully read while waiting in the quick start menu, then it does boot fine.

I feel this may be an EnvironmentLoader issue more than Aroma's, but I'm not 100% sure.

The expected behavior is for the Wii U to wait until the game disc is fully loaded and then launch it, I put a small video showing the differences and the message the Wii U uses for waiting for the disc.

https://user-images.githubusercontent.com/64707859/228303055-0854a8f6-6b35-4b7b-8d71-276ce6a6f96b.mp4

**Comment by Maschell** [comment]
Can you confirm it's fixed in Aroma Beta 14? I tried my best to match the original behaviour

**Comment by Cueropedo** [comment]
It does work very well! Will close the issue, thank you!
