### ISSUE TITLE
Custom C homebrew app makes you stuck on screen

### ISSUE THREAD

**Issue by Alfredoes234** [wiiu-env/Aroma#32]
I'm try to get Into programming custom firmware for the WIIU with the little resources there are and when I run the .wuhb app it's fine.
![tmp-cam-6294045552050483318](https://user-images.githubusercontent.com/114923333/230639310-fb19e6f3-20a0-4d1e-a89a-2b2b3fd3ac93.jpg)

But after trying to close it freezes

https://user-images.githubusercontent.com/114923333/230639362-8af50070-b4ab-4ec9-8f8a-dfa6596bc32c.mp4

So I don't know if I need to do something or its a bug on your side.

**Comment by Maschell** [comment]
Impossible to tell without seeing the code of the application. 
Did you implement the ProcUI loop properly?
Does it softlock or crash?

**Comment by Alfredoes234** [comment]
sure, but keep in mind I probably do have it wrong because the documentation for creating HB apps

**Comment by Alfredoes234** [comment]
sadly I couldn't import it through Github so here's a mediafire link (https://www.mediafire.com/file/e7j3ptstn1rdwuv/helloworld.rpx/file).

**Comment by Maschell** [comment]
Looks like the application is drawing to the screen while exiting. Make sure to only draw then the app is in foreground.

If you're using OSScreen, you can look at AromaUpdater's DrawUtils for having callbacks which handle this for your:

https://github.com/wiiu-env/AromaUpdater/blob/80f09f6c3e068a67920114508ddbce3eca42474e/source/utils/DrawUtils.cpp#L72-L73

**Comment by Alfredoes234** [comment]
Thanks dude
