### ISSUE TITLE
Surround is only stereo

### ISSUE THREAD

**Issue by Polypheides** [wiiu-env/Aroma#33]
Works fine in Tiramisu but not in Aroma

How i test: System Settings>tv>TV Sound Output Type>press sample "under" Surround should give 5 separate tones in front left, front right, center, surround left and surround right

In Aroma only 3 sound were played and all of them comes out of front left and front right.

Games tested in Tiramisu and Aroma was Lego Jurassic world.

Running latest update according to Aroma Updater.

**Comment by Maschell** [comment]
When using SwapSwapMe the sound gets mixed down to only Stereo, this might be the case?
