### ISSUE TITLE
CFW refuses to launch software installed by deleted users

### ISSUE THREAD

**Issue by AtlasC0R3** [wiiu-env/Aroma#35]
Without going into much details, I installed games, on my Wii U, with a user that is now deleted.
Using Tiramisu, I can play those games just fine with any user/profile on the system.
Aroma, however, refuses to do so; it gives me the usual lecture of:
> "This software cannot be used. The Nintendo Network ID used to purchase the software has been deleted." (next)
> "You need to purchase this software from Nintendo eShop again to be able to use it." ("go", leads to eshop; "cancel" leads to next dialog)
> "This software can be deleted by going to Data Management under System Settings. Go to the Data Management screen?" ("go" leads to data management screen to delete data, "cancel" returns to home screen and doesn't launch anything)

It's possible that I need to regenerate the title.tik files or whatever, or just reinstall the games, but considering Tiramisu handled this just fine (even playing different region games), I feel Aroma should somewhat handle this as well.

**Comment by Maschell** [comment]
No then restore the account? Otherwise: no support for piracy

**Comment by AtlasC0R3** [comment]
I hate to comment on old issues, really, but I just now wanted to play a physical, retail game via the disc (which, last I heard, can't be pirated) and it has also failed in a similar way (showing the game metadata without a problem, but once ingame throwing a "disc could not be read" error prompting me to eject and reinsert the disc) and then outright refused to reread the disc's metadata (saying it's an invalid disc) before a restart where all would repeat. Yet, it worked flawlessly with Tiramisu and in the stock firmware.
I think this issue has more merits than just for pirates. Your call, still; what can I do other than waste light resetting my Wii U all because of a fault that corrupted my account.
