### ISSUE TITLE
Can't Set Plugins Settings While Playing Shovel Knight Without Gamepad

### ISSUE THREAD

**Issue by filipe-maia** [wiiu-env/Aroma#38]
Hi.
I mostly use the pro controller, to save battery on the gamepad.
I can use the pro controller to access the plugin settings screen (by pressing L + down + minus), but then I can't go anywhere, only the gamepad works on the plugin settings screen while playing Shovel Knight.
While playing BOTW there is no problem.

**Comment by vaguerant** [comment]
Related, the eShop game A World of Keflings also has this issue. Was previously reported on Discord, just consolidating the info here. A Pro Controller can be used to play (as player two only) and to open the WUPS menu, but the menu cannot be interacted with or exited except via Wii U GamePad.

**Comment by Maschell** [comment]
Has been fixed with Arom Beta 17
