### ISSUE TITLE
Aroma only shows an Blank Screen

### ISSUE THREAD

**Issue by gomgo-github** [wiiu-env/Aroma#4]
I'm an Tiramisu User, but I tryed to install Aroma with EnviromentLoader, so I just added the Aroma Folder on to my SD card (on /wiiu/enviroments/aroma) and when I open my EnviromentLoader by pressing X on the BootUp and I try to open the aroma option, I just get a blank screen with the Wii U Menu Booting Music, aroma just doesn't boots (I'm using the last version [Aroma-beta-4])

Thanks

**Comment by Maschell** [comment]
Did you also update the EnvironmentLoader?

**Comment by gomgo-github** [comment]
How, by the Update Option? If then, yes, but if you mean update it by the SD Card, not, what files should I update on my SDcard?

**Comment by gomgo-github** [comment]
Ok, i just Updated the payload.rpx from [EnviromentLoader Repo](https://github.com/wiiu-env/EnvironmentLoader/releases/tag/v0.1) and now it just works fine! Thankyou so much!
