### ISSUE TITLE
i can't open the homebrew launcher

### ISSUE THREAD

**Issue by aguzoski** [wiiu-env/Aroma#41]
hi.
I have tiramitsu and aroma, in tiramitsu I can open homebrew without problem, but in aroma I can't, I tried to open it in the browser but then it gets stuck on a white screen, even in the homebrew launcher app happens.

**Comment by Maschell** [comment]
You don't launch Apps via the homebrew launcher, instead they appear on the Wii U Menu. If they don't show up on the menu they are not compatible. In this case you need to launch Tiramisu to be able to access the homebrew launcher

**Comment by Natedogwoooof** [comment]
> You don't launch Apps via the homebrew launcher, instead they appear on the Wii U Menu. If they don't show up on the menu they are not compatible. In this case you need to launch Tiramisu to be able to access the homebrew launcher
What happens if I hit icon limit.
