### ISSUE TITLE
150-3030 error while launching homebrew applicatons

### ISSUE THREAD

**Issue by Brian52** [wiiu-env/Aroma#43]
I just tried to homebrew my wiiu recently, and installed tiramisu and aroma environment. However, when I tried to launch homebrew applications (HB app store, reboot to tiramisu and wiiuident to be specific), I encountered the 150-3030 error. 
I tried to search for it and found that it is related to write permission on the SD card. So I tried to export my Mii and it successed. I also copied the files to varoius SD cards and redownloaded the aroma environment but all got this error. What can else can I try to fix it?

Btw, I'm using a 32GB japanese wiiu and I'm using aroma 15. Also, the homebrew apps works fine in tiramisu.

**Comment by Maschell** [comment]
Can you [dump the system crash logs](https://github.com/wiiu-env/WiiUCrashLogDumper) and send them to me via mail (maschell@gmx.de) or Discord (maschell)

**Comment by Maschell** [comment]
Can you try to delete/rename the `sd:\wiiu\homebrew_on_menu_plugin` directory on your sd card and try again?

**Comment by Brian52** [comment]
Thank you for your reply. 
I first tried to launch the aroma enviroment today, and it reports 150-3030 before reaching the wiiu menu. I dumped the log files from the tiramisu environment then I saw your second comment. I deleted the `sd:\wiiu\homebrew_on_menu_plugin` folder and it worked! I successfully launched the wiiu menu and got into the HB app store. 
Thank you for helping solving the problem.

**Comment by PNgamer71** [comment]
i delete homebrew on menu plugin, but when i go to my wii u menu there is not any homebrew app now
