### ISSUE TITLE
Error 150-3030 without SD Card being write-locked

### ISSUE THREAD

**Issue by Avad3** [wiiu-env/Aroma#44]
I have tried reinstalling tiramisu and reinstalling aroma and both of those did not fix. Could it be something to do with the SD Card reader on my console?

**Comment by Maschell** [comment]
To check if it's a hardware issue, check if the console detects the sd card at all:

Check if the console detects the SD card and can write to it:
- Start the console without any sd card.
- Open the Mii Maker
- Click on QR Code/Images, save Mii as image.
- Select any Mii to be saved as an image to the sd card

🟢 If saving the image was successful, the Wii U detecs the sd card properly.
🔴 If saving the image failed, the Wii U doesn't detect the sd card properly. Try another sd card, make sure the sd is not write locked, make sure it's FAT32 formatted, try a different micro sd adapter.

**Comment by V10lator** [comment]
Had a user with the same issue. Observations:
- Mii Maker able to save to the card
- Removing the folder didn't help
- Works with another SD card

**Comment by PNgamer71** [comment]
I have the same error i tried to delete homebrew on menu plugin, but when i went to the wii u menu there was no one app of homebrew, i tried to install the plugin again and make sure that the plugin of hiding the apps its disabled, then i went to the wii u aroma menu but the plugin was not there

**Comment by Maschell** [comment]
Backup your sd card, reformat and try again. (In case you used savemii or dumpling recently: Make sure to use latest dumpling and savemii in the future)

**Comment by PNgamer71** [comment]
Thanks it worked
