### ISSUE TITLE
After exiting homebrew app from home menu, black screen but input and audio work.

### ISSUE THREAD

**Issue by weegeeday** [wiiu-env/Aroma#5]
Using 5.5.3 JP of wiiu os, could be a problem specific to that version. 
After exiting dumpling, i got a black screen on the tv and wiiu gamepad.

**Comment by amberdambey** [comment]
Some homebrew apps aren't fully compatible with Aroma yet. As such, unexpected behavior may occur with such homebrew. Try testing if the behavior still occurs when using Tiramisu instead.


> could be a problem specific to that version

Try testing other homebrew (RPX, not WUHB). If the graphics issue still occurs, update to 5.5.6. If not, it's likely an issue with Dumpling.
