### ISSUE TITLE
After closing a GBA Game, Aroma is left with the "Wii U Menu" logo

### ISSUE THREAD

**Issue by Yersson9876** [wiiu-env/Aroma#59]
I started trying vc-GBA games and I realized that it does not close correctly and the Wii U has to be turned off forcibly, this happens with both original and unofficial games.

**Comment by Maschell** [comment]
Could not be replicated, please try again with latest beta

**Comment by Yersson9876** [comment]
The problem persist

**Comment by Maschell** [comment]
Then please provide more information on how to replicate this. Are you using any additional plugins/modules beside the ones that ship with aroma?

**Comment by Yersson9876** [comment]
I have the following: I'm going to leave a list of all the modules and plugins. I don't have the freeregion plugin that comes in the aroma pack, since some games show up in English even though they are in Spanish.


DIR:/fs/vol/external01/wiiu/environments/aroma/modules
/fs/vol/external01/wiiu/environments/aroma/modules/AromaBaseModule.wms
/fs/vol/external01/wiiu/environments/aroma/modules/ContentRedirectionModule.wms
/fs/vol/external01/wiiu/environments/aroma/modules/CURLWrapperModule.wms
/fs/vol/external01/wiiu/environments/aroma/modules/FunctionPatcherModule.wms
/fs/vol/external01/wiiu/environments/aroma/modules/KernelModule.wms
/fs/vol/external01/wiiu/environments/aroma/modules/MemoryMappingModule.wms
/fs/vol/external01/wiiu/environments/aroma/modules/NotificationModule.wms
/fs/vol/external01/wiiu/environments/aroma/modules/PatchMemoryRelocationsModule.wms
/fs/vol/external01/wiiu/environments/aroma/modules/PluginBackend.wms
/fs/vol/external01/wiiu/environments/aroma/modules/RPXLoadingModule.wms
/fs/vol/external01/wiiu/environments/aroma/modules/SDHotSwapModule.wms
/fs/vol/external01/wiiu/environments/aroma/modules/WUHBUtilsModule.wms

DIR:/fs/vol/external01/wiiu/environments/aroma/modules/setup
/fs/vol/external01/wiiu/environments/aroma/modules/setup/00_mocha.rpx
/fs/vol/external01/wiiu/environments/aroma/modules/setup/10_wums_loader.rpx
/fs/vol/external01/wiiu/environments/aroma/modules/setup/30_bloopair.rpx
/fs/vol/external01/wiiu/environments/aroma/modules/setup/01_sigpatches.rpx
/fs/vol/external01/wiiu/environments/aroma/modules/setup/30_nimble.rpx
/fs/vol/external01/wiiu/environments/aroma/modules/setup/99_autoboot.rpx

DIR:/fs/vol/external01/wiiu/environments/aroma/plugins
/fs/vol/external01/wiiu/environments/aroma/plugins/sdcafiine.wps
/fs/vol/external01/wiiu/environments/aroma/plugins/c2w_patcher.wps
/fs/vol/external01/wiiu/environments/aroma/plugins/ftpiiu.wps

DIR:/fs/vol/external01/wiiu/environments/aroma/plugins/config
/fs/vol/external01/wiiu/environments/aroma/plugins/config/ftpiiu.json
/fs/vol/external01/wiiu/environments/aroma/plugins/config/sdcafiine.json
/fs/vol/external01/wiiu/environments/aroma/plugins/config/gamepad_auto_standby.json
/fs/vol/external01/wiiu/environments/aroma/plugins/config/homebrew_on_menu.json
/fs/vol/external01/wiiu/environments/aroma/plugins/config/drc_sensorbar.json
/fs/vol/external01/wiiu/environments/aroma/plugins/config/padcon_plugin.json
/fs/vol/external01/wiiu/environments/aroma/plugins/config/Wii U Time Sync.json
/fs/vol/external01/wiiu/environments/aroma/plugins/config/Better_Settings.json
/fs/vol/external01/wiiu/environments/aroma/plugins/config/Gamepad_Volume_Changer.json
/fs/vol/external01/wiiu/environments/aroma/plugins/config/screenshot_plugin.json
/fs/vol/external01/wiiu/environments/aroma/plugins/config/SwipSwapMeAroma.json
/fs/vol/external01/wiiu/environments/aroma/plugins/config/evWii.json
/fs/vol/external01/wiiu/environments/aroma/plugins/config/WiiVCLaunch.json
/fs/vol/external01/wiiu/environments/aroma/plugins/config/inkay.json
/fs/vol/external01/wiiu/environments/aroma/plugins/config/aroma_base_plugin.json
/fs/vol/external01/wiiu/environments/aroma/plugins/config/wiiload.json
/fs/vol/external01/wiiu/environments/aroma/plugins/config/drc_read_result_spoofer.json
/fs/vol/external01/wiiu/environments/aroma/plugins/config/hid_to_vpad.json
/fs/vol/external01/wiiu/environments/aroma/plugins/config/region_free_plugin.json
/fs/vol/external01/wiiu/environments/aroma/plugins/Inkay-pretendo.wps
/fs/vol/external01/wiiu/environments/aroma/plugins/gamepad_auto_standby.wps
/fs/vol/external01/wiiu/environments/aroma/plugins/drc_region_free.wps
/fs/vol/external01/wiiu/environments/aroma/plugins/homebrew_on_menu.wps
/fs/vol/external01/wiiu/environments/aroma/plugins/drc-sensorbar.wps
/fs/vol/external01/wiiu/environments/aroma/plugins/padcon.wps
/fs/vol/external01/wiiu/environments/aroma/plugins/GiveMiiYouTube.wps
/fs/vol/external01/wiiu/environments/aroma/plugins/hidtovpad.wps
/fs/vol/external01/wiiu/environments/aroma/plugins/Wii_U_Time_Sync.wps
/fs/vol/external01/wiiu/environments/aroma/plugins/BetterSettings.wps
/fs/vol/external01/wiiu/environments/aroma/plugins/Gamepad-Volume-Changer.wps
/fs/vol/external01/wiiu/environments/aroma/plugins/screenshot.wps
/fs/vol/external01/wiiu/environments/aroma/plugins/swipswapme.wps
/fs/vol/external01/wiiu/environments/aroma/plugins/evwii.wps
/fs/vol/external01/wiiu/environments/aroma/plugins/WiiVCLaunch.wps
/fs/vol/external01/wiiu/environments/aroma/plugins/AromaBasePlugin.wps
/fs/vol/external01/wiiu/environments/aroma/plugins/wiiload.wps
/fs/vol/external01/wiiu/environments/aroma/plugins/drc_spoofer.wps

/fs/vol/external01/wiiu/environments/aroma/root.rpx
/fs/vol/external01/wiiu/environments/aroma/autoboot.cfg

**Comment by Maschell** [comment]
Try again with just the base aroma plugin. E.g. `Gamepad-Volume-Changer.wps` is known for causing issues

**Comment by Yersson9876** [comment]
That's right, I tried with the base aroma, without regionfree.wps or bloopair or other add-ons, and now it worked correctly. I will look for which module or plugin is causing the issue. Thanks for reply.

- add: I also had problems running COD: BOII, but the game runs normally now.
