### ISSUE TITLE
[Bug] Quick Start Menu doesn't update properly due to Icon Database redirection.

### ISSUE THREAD

**Issue by Cueropedo** [wiiu-env/Aroma#62]
When ECO Process runs on ECO Mode, it looks for the Icon Database in the MLC. If the game or application is not in that Icon Database (MLC), then Quick Start will fail to update when using Aroma.

One example of this issue is having the console running always Aroma, then using a new game disc that was never used with the console before, this will cause the SD Card Icon Database to get updated, but not the MLC one, producing a failure when Quick Start Menu tries to update, since the Icon is on the SD, but not on the MLC where ECO Process check.

**Comment by Maschell** [comment]
Will be (hopefully) fixed with the next release for the homebrew_on_menu plugin (see https://github.com/wiiu-env/homebrew_on_menu_plugin/commit/2c4a53aafdc0ac7f1c8addad2b6fd574de143f9f). I'll close that Issue if it's confirmed to be fixed
