### ISSUE TITLE
Notifications of plugins (Not aroma updates) not appearing in aroma

### ISSUE THREAD

**Issue by malik05051** [wiiu-env/Aroma#67]
After updating to beta 17 notifications of plugins like inkay don't shows even after updating to beta 20 same thing except if i only restart the aroma environnement using reboot it shows is there a fix ?

**Comment by Maschell** [comment]
Update to the latest Inkay version

**Comment by malik05051** [comment]
Checked for updates i'm running the latest version

**Comment by ashquarky** [comment]
We just pushed out an inkay update to fix this: [Inkay v2.5.0](https://github.com/PretendoNetwork/Inkay/releases/tag/v2.5.0)

**Comment by malik05051** [comment]
Yay it works thanks !
