### ISSUE TITLE
Clarification on if the sigpatches module is required for aroma?

### ISSUE THREAD

**Issue by Luca06Luwa** [wiiu-env/Aroma#7]
I only ask this as the current aroma documentation doesn't say that it requires it to boot.

**Comment by Maschell** [comment]
Sigpatches are **not** required to run any homebrew (.rpx, .wuhb files) with Aroma or Tiramisu.

**Comment by briantho** [comment]
what about games. I assume sigpatches are required to launch games, either legit titles, or fakesigned ones

**Comment by Maschell** [comment]
Legit title can always be launched without sig patches. It's not the scope of Aroma to allow launching title without a legit signature, in (almost) all cases this is piracy. The base aroma I'm providing will never be able to do this.

In terms of pure homebrew, Aroma **does NOT** need any sig patches. If you want to do piracy, go figure it out yourself. Aroma may not be the environment you're looking for, I don't care and don't support piracy of any form.
