### ISSUE TITLE
Wii U don't start

### ISSUE THREAD

**Issue by daniellopez12-code** [wiiu-env/Aroma#72]
After updating aroma I wanted to put something on the SD and I removed it and put the files in it. When I put it back in the Wii U 
doesn't turn on, it stays like that and only the background music of the menu is heard. But it turns on normally when I remove the SD.

https://github.com/wiiu-env/Aroma/assets/77121141/c58a8909-2195-4c00-a3af-aa9cc2515122

**Comment by Maschell** [comment]
Redownload Aroma. If this doesn't help, backup your sd card, **reformat** it and copy a fresh aroma installation on it.

By any chance: did you use savemii or dumpling in the past? These are known for corrupting the fat32 partition of your sd card. Reformatting will hell in these cases

**Comment by daniellopez12-code** [comment]
@Maschell i don't think so because i don't know what are that, but what do u mean with redownload aroma? just replacing the files? and i tried to do a backup my sd card but some files says to be "damaged" it says the error 0x80070570

**Comment by LordPapyrus** [comment]
Hi, just wanted to say that, it happens to me as well, i redownloaded aroma, but nothing happened. What do i do? I never used dumpling, and before downloading the update, it was all good...

**Comment by LordPapyrus** [comment]
Ok, small update, i fully redownloaded Aroma and now, it just shows me the "Wii U Menu" screen, with music playing in the background, other than that, it doesn't do anything...

**Comment by Maschell** [comment]
DId you **reformat** the sd card as I mentioned before?

**Comment by LordPapyrus** [comment]
No, i didn't do it yet.

**Comment by Maschell** [comment]
Another source of bootloop is the `sd:/wiiu/environments/aroma/plugins/SNTP-Client.wps` plugin on the sd card. It's broken and causes undefined behaviour. Remove it if you have it and use [Wii U Time Sync](https://github.com/Nightkingale/Wii-U-Time-Sync) instead.

**Comment by LordPapyrus** [comment]
Thanks man, i did as you said and it was all fixed!

**Comment by Nandru86** [comment]
> Another source of bootloop is the `sd:/wiiu/environments/aroma/plugins/SNTP-Client.wps` plugin on the sd card. It's broken and causes undefined behaviour. Remove it if you have it and use [Wii U Time Sync](https://github.com/Nightkingale/Wii-U-Time-Sync) instead.

Thanks!! Had the same issue and it was caused by that plugin

**Comment by daniellopez12-code** [comment]
ty man it helped me to
