### ISSUE TITLE
Quick Start Menu Issues

### ISSUE THREAD

**Issue by Knkaku** [wiiu-env/Aroma#74]
I've been using Aroma Beta 21 and have been having fun setting my splash screen as a PNG in the right position. However, after setting the splash screen and leaving it in the Quick Start Menu for a while, I discovered that my Wii U would soft lock on the transition screen to the Wii U Menu. In fact, this was recorded in the console's crash log. Can this be fixed?

**Comment by Maschell** [comment]
Can you upload the crash log?

**Comment by Knkaku** [comment]
[sysconf_crashlog_0_20240712_082724.txt](https://github.com/user-attachments/files/16184617/sysconf_crashlog_0_20240712_082724.txt)

**Comment by Knkaku** [comment]
[54.log](https://github.com/user-attachments/files/16190127/54.log)

Changed to the one obtained from Wii UCrashLogDumper. Sorry for the inconvenience of re-uploading.

**Comment by Maschell** [comment]
don't worry, it's the same crash log!
How exactly are you triggering this? I could reproduce it by waiting on the quick start menu until the console was started (~25 seconds) and then click on "Wii U Menu" on the Wii U Menu. This seems to be the same crash.

Thanks for the report, I'll look into this

**Comment by Knkaku** [comment]
Sorry, I couldn't explain it well. I'm Japanese and I'm reporting here using a translation app. It crashed with the same steps you said.
