### ISSUE TITLE
vwii support for aroma???

### ISSUE THREAD

**Issue by briantho** [wiiu-env/Aroma#8]
hi, would it be possible to add support for aroma for vwii. I would love to be able to use plugins with vwii. for example, imagine using bloopair with mario kart wii so that you could use a ps4 controller with mario kart wii. That would be amazing. Is there any possibility to add support for this?

**Comment by Maschell** [comment]
This is not possible. The Wii U is rebooting into Wii Mode which unloads any Wii U features. Aroma is only running in Wii U mode.
