### ISSUE TITLE
Games doesent read amiibo 

### ISSUE THREAD

**Issue by memohomebrew** [wiiu-env/Aroma#81]
Hi,i just bought a cat mario amiibo,it was in the box,it works good but when i used the amiibo my games dint readed it maybe is cause the environtment? help me

**Comment by Maschell** [comment]
Make sure you are  NOT using re_nfp. While re_nfp is loaded, no real amiibos will work

**Comment by memohomebrew** [comment]
i just deteled it,tried again and dint work

**Comment by Maschell** [comment]
Did you delete the module as well?

**Comment by memohomebrew** [comment]
ima check

**Comment by memohomebrew** [comment]
i dont have re nfpii module

**Comment by memohomebrew** [comment]
oh so thank you
