### ISSUE TITLE
.rpx extension

### ISSUE THREAD

**Issue by ZweiBR** [wiiu-env/Aroma#84]
Is it possible to remove the recognition of the .rpx extension in the next update of the aroma?
The .wuhb extension does not appear in tiramisu

**Comment by Maschell** [comment]
1. .rpx are already supported.
2. Why do you still want to use Tiramisu? We should focus on porting stuff over to Aroma instead of porting back to Tiramisu

**Comment by ZweiBR** [comment]
I use Aroma.
I meant to remove support for the .rpx extension so it doesn't appear in Aroma.
