### ISSUE TITLE
Aroma remains locked after 20 version

### ISSUE THREAD

**Issue by pepelogica** [wiiu-env/Aroma#85]
Every time I start WiiU and select Aroma display, the set up system remains locked at the WiiU initial logo, it does not keep going any further. I cannot use any other version apart from the 20th as it remains blocked. I will really appreciate any word of advice.

**Comment by Maschell** [comment]
Delete the sntp plugin form the sd card

**Comment by pepelogica** [comment]
thank you very much everything works

**Comment by Maschell** [comment]
sd:/wiiu/environments/aroma/plugins
